### ISSUE TITLE
Nametags too large

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#106]
The nametags are obviously larger than before.
For the nametags we usually use they should be about 8,9 x 5,3 cm

**Comment by fw42** [comment]
Are they too high or too wide? They should be 8cm x 5.5cm, according to the CSS that I'm using (so only a little bit too high). Did you actually try to print one?

**Comment by Laura-O** [comment]
Yes, printed them and they are 9cm x 6,5cm.
Also checked my printer settings and printed from another computer - same result.

**Comment by fw42** [comment]
Unfortunately this is a lot of trial and error (and I don't have a printer).

Can you use Chrome and manually edit the CSS to find the optimal value? Open the page and right click on someone's name and click "Inspect element". Pick one of the table cells ("td" element). On the right, you can modify the values for the CSS.

![screen shot 2015-04-05 at 10 09 05 am](https://cloud.githubusercontent.com/assets/2072686/6997100/e1a74bde-db7b-11e4-88fb-6d37f014bad8.png)

If you tell me which values work best for you, I can change it.

I guess I could make this a configuration options if necessary.

**Comment by Laura-O** [comment]
Ok, I found  [this](http://stackoverflow.com/a/28132441/4403398) and set the body width to 210mm and it worked. :-)
It would be cool if you could also set the height to 5,3cm.

**Comment by fw42** [comment]
@Laura-O: I just deployed the fix. Can you confirm that it's good now?

**Comment by Laura-O** [comment]
Yes, thank you!
