### ISSUE TITLE
Cannot select owner when creating competition

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#107]
And so, currently new competitions cannot be created. :/

![image](https://cloud.githubusercontent.com/assets/3089192/6996901/99bef9d8-dba4-11e4-9e4b-a640c15c8f93.png)

**Comment by fw42** [comment]
Does it give you an error when you don't select an owner and try to save it? Setting an owner should be optional.

The usual workflow for me so far was (1) create competition, (2) create user or edit existing user and give them permission to see the competition, (3) go back to edit the competition (you should see the owner now -- only staff members of a competition can be owners).

I agree that that's kinda annoying. I will see if I can change that.

**Comment by SAuroux** [comment]
Oh, ok. I didn't think about that, as I expected to be able to select an
ower from all available users when creating a competition.

2015-04-05 15:08 GMT+02:00 Florian Weingarten <notifications@github.com>:
