### ISSUE TITLE
Add button for "already paid"

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#108]
![image](https://cloud.githubusercontent.com/assets/3089192/6996922/6a7ea992-dba5-11e4-9001-d4fba070f5f9.png)

With our frequently used pre-payment system this has to be selected for almost all competitors, currently by editing the person, scrolling, checking the right check box and saving, which is quite annoying.

**Comment by SAuroux** [comment]
thanks. :)

One minor comment: I noticed that this button also apperas for people with Free entrance, which is rather useless.

**Comment by fw42** [comment]
true. will fix.
