### ISSUE TITLE
Mobile compatibility issue on Android

### ISSUE THREAD

**Issue by suushiemaniac** [fw42/cubecomp#118]
Trying to access the website on Android 5.1, Firefox Mobile 37.0.1 by simply typing the URL (no typos) results in:
"An error occured during a connection to admin.cubecomp.de. The OCSP server has no status for the certificate. (Error code: sec_error_ocsp_unknown_cert)"

**Comment by fw42** [comment]
hm strange, no idea what that is. The SSL certificate is pretty recent. I will take a look. Although the admin's design probably isn't very responsive anyway (will not look good on mobile).

I haven't tested any of the pages with mobile yet. On my TODO list.

**Comment by suushiemaniac** [comment]
Desktop Firefox (also 37.0.1) works just fine. Might be a browser-side issue
