### ISSUE TITLE
Alternative financial model support

### ISSUE THREAD

**Issue by suushiemaniac** [fw42/cubecomp#127]
The settings page only supports entering entrance fees for individual days and then calculates the price for multiple days by adding the values.
The payment system I'm using costs 7.50 euros for either single day but 10 euros for both days instead of 2*7.50 = 15. I'd like to have an option to enter such an alternative price model (which existed in the old admin panel, afaik?) so that the dashboard financial calculations are correct.

**Comment by fw42** [comment]
yep that's on my todo list (see https://github.com/fw42/cubecomp/issues/17)

will add this soon (going on vacation now though for a week)

**Comment by fw42** [comment]
closing this issue since the feature request is already mentioned in https://github.com/fw42/cubecomp/issues/17. thanks for reporting though, I wasn't sure if anyone uses this.
