### ISSUE TITLE
Editting registration comments

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#128]
I'd like to be able to edit registration comments as it was possible in the previous version. 

The goal is, to remove unnecessary information from the checklist, usually by removing the registration comment and aggregating important information as an admin comment.

**Comment by fw42** [comment]
How about I just hide the user comments by default from the checklist? If the only issue is that the checklist is too noisy, would that be enough? I kinda don't like the idea of admins editing the user comments...
