### ISSUE TITLE
Entrance fees automatically displayed on registration page

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#131]
This is actually more an issue than a feature:

- it is misleading if competitions have combined fees for multiple days, like 10€ for one day, 15 € for two days, which is quite common
- for German Open 2015, I had entered 4,55 € as this is what I receive after Paypal removes its fees. I didn't know that this was automatically displayed somewhere and was told by someone who noticed it today.
- also, after now entering "5", the page shows "5.0 €"

I think I would prefer to simple remove this from the registration page.

**Comment by fw42** [comment]
I see. Ok, will remove it. For now, just remove the "currency" setting in the competition settings, which will disabled this.
