### ISSUE TITLE
csv export formatting request

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#134]
These days, most competitions use cubecomps.com to manage the data entry. As an import format, cubecomps.com requires an excel file with the following corresponding cvs format:

Name,Country,WCA ID,Gender,Birthdate,,,,[events]

It would be great if cubecomp could produce the csv export the same way!

**Comment by fw42** [comment]
you mean in addition to the current format? or instead of?

**Comment by SAuroux** [comment]
Instead. Basically this doesn't change much besides switching gender and
DoB.
Am 17.04.2015 02:11 schrieb "Florian Weingarten" <notifications@github.com>:
