### ISSUE TITLE
Rename "disabled" to "cancelled"?

### ISSUE THREAD

**Issue by fw42** [fw42/cubecomp#158]
Suggested by @cubizh 

> On the competitors management page, I would like to suggest the usage of the word "Cancelled" instead of "Disabled" regarding the competitor state, as at first I thought it was a field to warn organizers about the disability of the competitor and not a cancelation of the registration.

@sauroux, does this make sense to you?

**Comment by SAuroux** [comment]
Yes, sure. :)
Am 08.05.2015 04:21 schrieb "Florian Weingarten" <notifications@github.com>:
