### ISSUE TITLE
Printable personalized event schedules

### ISSUE THREAD

**Issue by fw42** [fw42/cubecomp#159]
Suggested by @cubizh 

> If you have nothing else to do and want a nice challange this is a nice one to have for big competitions. This idea was made I think for the World Championships, which was to print on the backside of the competitor nametags each competitor's schedule (the times of the events they were registered to participate in)

**Comment by Laura-O** [comment]
The main purpose of these schedules is probably to have an overview of the
heats/groups you are competing in. As the grouping isn't done here, it's
not possible to do that.

I thought about a feature request to have a simple function for grouping
here (divide n competitors in x equal groups) but I don't think anyone
really needs this.

2015-05-08 4:23 GMT+02:00 Florian Weingarten <notifications@github.com>:

**Comment by fw42** [comment]
Good point, Laura

**Comment by cubizh** [comment]
I agree, this and Laura's suggestion is something interesting mostly for larger competitions where you really need to define groups in a more thoughtful way and in advance.
I only thought of this due to the automated nametag printing being already implemented.
