### ISSUE TITLE
Issues in comparison tables 

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#184]
For 3BLD competitors are ranked by their mean time. The format in competitions is always "Best of 1" so these rankings are misleading.

Minor issue:
FMC is also ranked by the mean of 3 results. This makes more sense, but as it can be held as "Best of 1/2" or "Mean of 3"  in competitions it would be nicer to have an option to display the appropriate rankings or just display a ranking for both.

**Comment by suushiemaniac** [comment]
Maybe even determine the sorting criteria for each competition independently?
For example, organisers are free to hold 6x6 and 7x7 either as "Mean of 3" or as "Best of 1/2". Depending on the actual competition schedule, the psych sheets would then be automatically sorted by Single or Mean respectively.
Or at least include an option in the Admin Panel event administration to choose the psych sheet ordering criteria for each event manually?

**Comment by fw42** [comment]
> For 3BLD competitors are ranked by their mean time. The format in competitions is always "Best of 1" so these rankings are misleading.

The rankings on the comparison page are the same as the rankings in the WCA database (and on the WCA website), i.e. [here](https://www.worldcubeassociation.org/results/events.php?eventId=333bf&regionId=&years=&show=100%2BPersons&average=Average) the 3BLD results are also not ranked by Best of 1. That's pretty much the only reason why I did it this way. It was just the simplest to implement and it seemed reasonable to keep the ranking the same way it is on the WCA website.

**Comment by fw42** [comment]
Hmm maybe I misunderstood you. Are you saying I should just sort by single instead of by average for that category?

**Comment by fw42** [comment]
I added a dropbox so that you can pick what to sort by. Try it out [here](https://cubecomp.de/go16/de/comparison?event=333bf&sort_by=single).

![screen shot 2016-04-08 at 19 34 30](https://cloud.githubusercontent.com/assets/2072686/14400037/f7e15332-fdc0-11e5-8365-00930b05ba7b.png)

I hope this makes sense to you. Let me know if not.
