### ISSUE TITLE
Mails are sent from cubecomp@cubecomp.de

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#185]
When writing mails to competitors via the interface the sender is cubecomp@cubecomp.de.
That's really bad as we do not receive the replies. It would be good if this could be changed to the individual personal mail address.

**Comment by fw42** [comment]
This is on purpose. The mailer sets a Reply-To address which almost all email clients respect. To prove you wrong: cubecomp@cubecomp.de goes to my personal inbox and I haven't received a single competitor email yet that was meant to be delivered to the organizers.

Changing the From address to be the staff email would make most email servers either reject the email or at least categorize it as spam (depending on the domains [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework) record settings).

**Comment by fw42** [comment]
So long story short: The replies already go to the staff email, unless your email client is a piece of shit :-)

**Comment by Laura-O** [comment]
OK, my bad. I didn't see the reply-to, some everything fine. :-)
