### ISSUE TITLE
Nationality in registration form

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#186]
We had some issues with competitors interpreting that "Land" or "Country" in the registration form means the country where they are currently living and not their nationality.
It would be cool if this could be changed to "Nationalität" and "Nationality".

**Comment by fw42** [comment]
Good point. Will change.

**Comment by SAuroux** [comment]
Well, this looks really strange now. Why not "Nationalität" and "Nationality" as suggested by @Laura-O ?

**Comment by fw42** [comment]
Because "Nationality: Germany" makes no sense ("Nationality: German" would be correct, but the WCA stores countries, not nationalities).

**Comment by fw42** [comment]
so in order for me to do what laura suggested, I would need to convert all the WCA country names to nationalities and keep a mapping so I can convert between them later (the CSV export again wants the country name, not the nationality)

**Comment by fw42** [comment]
I can change it to Nationality and keep the country name, but I think "Nationality: Germany" looks stupid... but if you think that's fine then I can change it..

**Comment by SAuroux** [comment]
You are technically correct, but according to my experience it is common practise to list countires in a dropdown for nationality. But the WCA site also uses "Citizen of" indeed. Well, let's keep it as is then. :)
