### ISSUE TITLE
Selecting WCA ID should fill correct names in registration

### ISSUE THREAD

**Issue by cubizh** [fw42/cubecomp#187]
Currently, when you choose the WCA ID in registration, the last name is not properly chosen, but the second name only.
Example: 2003BRUC01 (Ron van Bruchem)
First name: Ron
Last name: van

**Comment by timhabermaas** [comment]
Could #21 be a reasonable solution? I'm not sure whether it's possible to reliably extract the first and last name from the WCA data.

**Comment by cubizh** [comment]
Sorry, I didn't see that closed issue.
Yes, I think using just one field for the name would probably be a good decision, particularly when you have multiple last names, competitors don't know if they should put all or just 1, while just one field that question wouldn't rise.
The instances where the first name only is used vs full name are neglectable in my view (email template).

**Comment by fw42** [comment]
Gonna close this issue since it's basically identical to https://github.com/fw42/cubecomp/issues/21.
