### ISSUE TITLE
Wrong stats on nametags

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#188]
There's obviously a problem with the stats on the nametags: e.g. my current nametag from Franconia Open says "71th competition" although this is my 72th competition.
Maybe there is just a +1 missing? :-)

**Comment by fw42** [comment]
yep, you are right. will fix that soon.

**Comment by cubizh** [comment]
Yes, I noticed this too, as I was about to print. Also, the "th","nd", "rd" may break over translation to something other than english. In portuguese, you'd just need to use "<number>ª competição".  But it's a nice idea.
