### ISSUE TITLE
Importing theme error

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#190]
Björn tried to import the Munich Open 2014 theme for Munich Open 2015. However, he got the following error message.

"We're sorry, but something went wrong. If you are the application owner check the logs for more information."

I tried as well and could repoduce the error. Now, two hours later, I still get the same error message. I also tried to import one of the default themes, which changed nothing (same error).

**Comment by fw42** [comment]
Interesting. Other competitions work? Just Munic Open 2015 doesn't?

**Comment by fw42** [comment]
I just tried another competition which also doesn't work. Might be related to one of the updates I did recently. Will take a look.

**Comment by fw42** [comment]
Should be fixed (https://github.com/fw42/cubecomp/commit/049b11a01e56b681f8672e535bcd8844c3d11d76).
