### ISSUE TITLE
About the use of "local city" on the competitors list

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#191]
After a recent discussion on the delegates mailing list, I noticed that the use of the local city (like Köln (K) for German nationals 2015) violates a regulation about confidential data:

2d) A competitor's name, country, gender, and competition results are considered public information. All other personal information is considered confidential, and must not be disclosed to outside organisations/persons without the consent of the competitor.

So, strictly going by this, we have two options:
1) disable this feature.
2) Clearly ask for consent in this option, such as "I live in Köln and I give consent that this information will be displayed on the registration list."

On a more general note, I wonder if the feature actually has any use, so 1. might be the easiest solution. But I don't feel strongly about this. Also, since there has never been a complaint about this in 5 years, it could be ok to go with another option:

3) Assume that consent is given by checking that box and leaves things as they are for now.

Any thoughts?

**Comment by fw42** [comment]
4) show the information only to the organizers, but not to other competitors

**Comment by fw42** [comment]
@cubizh what do you think?

**Comment by cubizh** [comment]
To me, the local city is a perfectly neglectable field, I don't use it for anything, so you can scratch it if you want or change it's behaviour.

**Comment by Laura-O** [comment]
The local city is still displayed on the nametags. This should be removed as well.
