### ISSUE TITLE
Choices for event length

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#196]
The options from 5 minutes to 120 minutes are sometimes insufficient. Right now, I would like to set a length of 150 for 4x4x4 BLD and 5x5x5 BLD at German Nationals on the side stage.

I would suggest extending all the 5 minute steps up to 180 minutes and further 30 minute steps up to 8 hours. That should pretty much cover all the use cases.

Alternatively, the length could be changed to a text field with free input.

**Comment by fw42** [comment]
@SAuroux should be fixed now
