### ISSUE TITLE
Event overview has wrong registration numbers

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#199]
The numbers for registrations in the events table is wrong.
According to the dashboard there are 97 competitors registered for German Nationals on Sunday, but 98 compete in 3x3. I assume *all* registrations are counted, also non-active registrations.

**Comment by fw42** [comment]
I assume you mean this:

<img width="662" alt="screen shot 2015-08-19 at 7 42 10 pm" src="https://cloud.githubusercontent.com/assets/2072686/9372245/76f694ee-46aa-11e5-909c-1a7f5a33698c.png">

If so, then you are right, that includes all competitors (even new and cancelled ones). If you click the little magnifying glass icon for "Show registrations", you can see which ones are not confirmed.

Do you think it should be changed to only show the ones that are confirmed, i.e. not new and not cancelled? Or maybe confirmed and new but not cancelled?

**Comment by fw42** [comment]
Also the number includes the waiting ones... Not sure if that comes up a lot, but might also be confusing... so if it says "20 (10 waiting)" then that's a total of 20, not 30.

Let me know what you think makes the most sense and I will change it.

**Comment by Laura-O** [comment]
For me, showing the registered and confirmed (not new, not canceled, not waiting) makes most sense.
At least that is how I interpreted it in the past. ;-)

Do you agree, @SAuroux?

**Comment by SAuroux** [comment]
I agree. ;)

2015-08-21 13:19 GMT+02:00 Laura Ohrndorf <notifications@github.com>:
