### ISSUE TITLE
Confirmation mails marked as spam

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#203]
I was contacted by a new competitor who asked why he didn't receive a confirmation mail. He later found out that it was marked as spam by GMX. We had some issues with competitors registering twice recently, I'm not sure why they did that, but this might be the reason.
I also tested to register with my Gmail Account and found the mail in the spam folder. There's no further information why it was identified as spam.

**Comment by fw42** [comment]
I have an idea what might be the reason for this. Will look into it soon.

**Comment by fw42** [comment]
This should be a bit better now... Let me know if it still happens often.

**Comment by fw42** [comment]
I switched to a different mail provider and this should be much better now. Will close it for now. Please reopen if you see this happening again.

**Comment by Laura-O** [comment]
There seems to be something wrong with this fix. After sending the email, the "We're sorry, but something went wrong."-page appears and the email is obviously not sent (just tested by sending a mail to myself, which didn't arrive after 10 minutes).

**Comment by fw42** [comment]
Thanks for reporting this so quickly. It should be fixed now. My bad.
