### ISSUE TITLE
Remove "Newcomer"-comment for guest from checklist

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#204]
(I thought that had been mentioned before, but I couldn't find it. So sorry if this is a duplicate.)

On the checklist everyone with no WCA ID has a comment "Newcomer (Check identification!)", not differentiating between competitors and guests.
As we don't check IDs of guests that's not necessary and might also be confusing for registration staff.

**Comment by fw42** [comment]
Thanks for the bug report!

**Comment by Laura-O** [comment]
Thanks a lot for fixing all these issues so fast. :-)
