### ISSUE TITLE
WCA database script not working on Mac OS X

### ISSUE THREAD

**Issue by Laura-O** [fw42/cubecomp#209]
I installed cubecomp on Max OS X 10.11.
When importing the WCA database the update script stops with the error message:
> sed: -i may not be used with stdin

This can be fixed by moving the filename to the end of the line: 
> sed -i -e "s/CHARSET=latin1/CHARSET=utf8/g" $FILENAME

I think that won't work on Linux so I am not creating a pull request for this. Maybe that's something that should be added to the Readme?

**Comment by fw42** [comment]
oh yeah, damn. the syntax for `sed` is slightly different on OS X..

We can make the script itself check if it's running on Linux or Darwin and then do the right thing based on that..

```
if [[ "$(uname -s)" == "Darwin" ]]; then
  do darwin things
else
  do linux things
fi
```

this kind of thing. Can you make a PR?
