### ISSUE TITLE
Bug in Stats

### ISSUE THREAD

**Issue by SAuroux** [fw42/cubecomp#211]
The second stats graph seems to be off by a month: https://cubecomp.de/go16/de/stats

Also, for Hessen Open, there are two data points for one date (maybe due to the same issue?): https://cubecomp.de/he16/de/stats

**Comment by fw42** [comment]
Not sure where the duplicate datapoint thing came from... but looks like my fix solved both issues. Thanks for letting me know,

**Comment by timhabermaas** [comment]
JS interprets `new Date(2014, 12, 1)` as the 1th of January 2015. This might've been the cause of the duplicate point.

**Comment by SAuroux** [comment]
well, I guess the duplicate came from calling data from 30th of February. :)

Thanks for fixing this so quickly!

2016-02-01 17:12 GMT+01:00 Florian Weingarten <notifications@github.com>:
