### ISSUE TITLE
Wrong weekday for birthdays

### ISSUE THREAD

**Issue by LinusFresz** [fw42/cubecomp#230]
View competitor "Linus Fresz" in admin/user-mode at the competitors list for German Nationals 2016 for this issue.
His birthday is at the Sunday of the competition (09.10), cubecomp says "Birthday on Monday". I guess this happens from that the competition starts on Friday, but somehow cubecomp starts counting the date from Saturday, so the date gets shifted to one day later.

**Comment by LinusFresz** [comment]
I also experienced another error of the same kind: For Austrian Open 2016 one person has birthday on Saturday, but her birthday is displayed with "Birthday on Wednesday".

**Comment by fw42** [comment]
Thanks. Will take a look as soon as I'm back from vacation.

**Comment by Laura-O** [comment]
In case it is not obvious what is happening here: the weekday shown is the weekday of the actual birthday of the competitor (`competitor.birthday.strftime("%A")`, not the weekday of his birthday in the year of the competition.

However, my knowledge about Rails is too bad to fix that.... :-)

**Comment by fw42** [comment]
Ah, thanks for looking into that, Laura. You should give it a try and see if you can figure out a fix! Would be a good learning opportunity. Feel free to message me if you need help.

**Comment by fw42** [comment]
This should now be fixed, thanks to Laura.

<img width="523" alt="screen shot 2016-05-26 at 08 40 37" src="https://cloud.githubusercontent.com/assets/2072686/15574833/96aaffc8-231d-11e6-95ab-89f1d1bc060e.png">
