### ISSUE TITLE
Swiss Nationals: Psych sheet error

### ISSUE THREAD

**Issue by LinusFresz** [fw42/cubecomp#233]
A small bug report:
For the competition Swiss Nationals 2016 (and only this competition) I have an issue with the comparison page:
https://cubecomp.de/swn16/de/competitors
when I click on 'vergleich' the new page loads and is says 
_Liquid error: comparison of Fixnum with nil failed_
Same for the comparison page with the other languages available.

**Comment by fw42** [comment]
should be fixed, thanks for the bug report

**Comment by LinusFresz** [comment]
Just kind of fixed.. For some reason there is only a psych sheet for 2x2, 3x3, 4x4, OH and Square-1. All other events are missing. Does this happen because of a 'wrong' entry in the event section from the organizer?

**Comment by fw42** [comment]
yea you need to use the "Load WCA event" (or whatever it's called) button when creating the events
