### ISSUE TITLE
Lichtenstein missing as a country

### ISSUE THREAD

**Issue by LinusFresz** [fw42/cubecomp#234]
Due to a registration for Swiss Nationals 2016 I noticed that Lichtenstein is missing in the list of Countrys. Can it be added?

Best,
Linus

**Comment by fw42** [comment]
This was fixed in https://github.com/fw42/cubecomp/pull/235

<img width="605" alt="screen shot 2016-08-16 at 19 30 21" src="https://cloud.githubusercontent.com/assets/2072686/17719353/eb804822-63e7-11e6-86b9-04d2b1570fb7.png">
