### ISSUE TITLE
Suggest corrections for typos in email address etc.

### ISSUE THREAD

**Issue by fw42** [fw42/cubecomp#5]
One common problem in the old website was that people would often misspell their own email addresses which then would have to be manually corrected (if even noticed at all).

Would be nice to match a new competitor registration to existing registrations with the same name or same WCA ID and suggest a correction if the email address of the new registration is different than an email address of an old registration.

Also suggest fixes for common typos (such as .co instead of .com).

**Comment by fw42** [comment]
For my own future reference:

```ruby
aliases = {}

result = ActiveRecord::Base.connection.execute(%q{
  SELECT first_name, last_name, GROUP_CONCAT(DISTINCT(email) SEPARATOR '|') FROM competitors
  GROUP BY first_name, last_name HAVING COUNT(DISTINCT(email)) > 1
}).to_a

result.each{ |u| addrs = u.last.split("|").map(&:downcase); addrs.each{ |a| aliases[a] = addrs - [a] } }

aliases
```

Gives a hash that maps email addresses to known other addresses of the same person.

**Comment by timhabermaas** [comment]
[These guys](https://www.gosquared.com/blog/login-screen-design-flow) use [Mailcheck](https://github.com/mailcheck/mailcheck) to point out common errors in email addresses.

btw. Have you thought about sending confirmation emails? This would be the most foolproof method to make sure the user didn't mess up.

**Comment by fw42** [comment]
Interesting. That's kinda cool! I like that JS thing. We should totally use that.

I would like to avoid confirmation emails if possible, that seems like too much imho (do you disagree?). It's not really *that* important that an email address is valid. It's just a bit annoying (mostly for the competitor, not for us).

**Comment by timhabermaas** [comment]
> do you disagree?

I'm not sure. Sending an email is the only way for organizers to contact competitors (about missing payments, canceled events etc.). But confirming your email every time you register for a competition might get annoying. Maybe make it "Confirm your registration"? Or make it an option to require confirmation? ¯\\_(ツ)_/¯

**Comment by fw42** [comment]
@SAuroux what do you think?

**Comment by Laura-O** [comment]
One problem I see with automatic confirmation mails is that people might mistake them as a confirmation for their registration. When we use a prepayment system this might not be helpful.

**Comment by fw42** [comment]
I would say lets try the Mailcheck JS thing and if organizers still see a lot of broken email addresses, we can still implement confirmation emails later. I also added an MX record check (https://github.com/fw42/cubecomp/pull/125), so that should catch at least many typos in the domain part.
